# Dockerfile.routes
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all project files
COPY . .

# Expose FastAPI port
EXPOSE 8080

# Run FastAPI app
CMD ["uvicorn", "routes:app", "--host", "0.0.0.0", "--port", "8080", "--workers", "2"]