version: '3.8'

services:
  routes:
    build:
      context: .
      dockerfile: Dockerfile.routes
    command: uvicorn routes:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - streamlit
    networks:
      - webnet

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    command: streamlit run scene_sense_app.py --server.port 8501 --server.enableCORS true
    ports:
      - "8501:8501"
    env_file:
      - .env
    networks:
      - webnet

networks:
  webnet: